### ISSUE TITLE
White screen crash when changing the location of 3d models

### ISSUE THREAD

**Issue by arxarinze** [RodrigoHamuy/react-three-map#115]
I assume this was meant to host models in one location, however when changing location of a model, the app can sometimes crash leading to a white screen. Is this a normal occurence?

**Comment by RodrigoHamuy** [comment]
Is there a way to replicate this issue? Ideally a codesandbox?

At least for me, things are working as expected when you change lat/lon: https://rodrigohamuy.github.io/react-three-map/?story=load-ifc-model--default

**Comment by arxarinze** [comment]
Its a Webview problem on ios, i think the memory of the scene crashes the Webview. Wonderful plugin, works execellent.
