### ISSUE TITLE
Layer with id "jsx-layer-0" already exists on this map

### ISSUE THREAD

**Issue by Igor-Vuk** [RodrigoHamuy/react-three-map#120]
With the new mapbox-gl 3.5.2 version I keep getting error **Layer with id "jsx-layer-0" already exists on this map"** that is triggered by Canvas from react-three-map.  By using mapbox-gl version 3.5.1 everything is ok.

**Comment by RodrigoHamuy** [comment]
@Igor-Vuk would you be able to provide a sandbox to reproduce?

You can start by forking from this one: https://codesandbox.io/p/sandbox/react-three-map-gettings-started-dhw34w

Thanks!

**Comment by Igor-Vuk** [comment]
seams to be fixed with the latest version of mapbox-gl 3.6.0
