### ISSUE TITLE
3d model rendring in map 

### ISSUE THREAD

**Issue by m6hdix** [RodrigoHamuy/react-three-map#123]
I am experiencing a bug when rendering multiple 3D models using react-three-map and react-three-fiber. Despite having different URLs for the models, the same model is rendered across all canvases. This issue occurs when trying to load multiple models that are close to each other on the map.

Expected Behavior:
Each canvas should render the 3D model specified by its unique URL and fils.

Actual Behavior:
All canvases render the same model, ignoring the distinct URLs and file .
[https://github.com/RodrigoHamuy/react-three-map/issues/url](url)

**Comment by RodrigoHamuy** [comment]
duplicated: https://github.com/RodrigoHamuy/react-three-map/discussions/122
