### ISSUE TITLE
Documentation site created using readme wanting review and possible approval

### ISSUE THREAD

**Issue by emmz3230** [RodrigoHamuy/react-three-map#127]
* i created a Documentation site by interpreting your readme to docusarus

* Will love to be check by the project maintainer.
* will love to get reviews from project maintainer.
* not really asking for any pay just need to know if i can help with that and use in my portfolio.
* thanks 
* will love to hear back from you
* i can share source code with you

**Comment by RodrigoHamuy** [comment]
Hey @emmz3230 thanks a lot this. At the moment, I'm not looking to expand the documentation or its format, but I really appreciate your interested. Thanks
