### ISSUE TITLE
THREE.Shape() & <extrudeGeometry args={[shape, options]} />

### ISSUE THREAD

**Issue by forerunrun** [RodrigoHamuy/react-three-map#64]
First and foremost, what an incredible feat you're achieving with this repo, it's the perfect solution for using R3F in a maps environment! 

I've been playing with the library for a week or so, everythings been absolutely delightful being able to add R3F components as an overlay and the ability to extend THREE graph with drei! 

one limitation that I've stumbled on is some sort of matrix mismatch when trying to use a `THREE.Shape()` as a basis for `<extrudeGeometry/>`, it looks like maybe one of two (or both) things are happening, a matrix transformation is being applied on the shape before it's passed as a prop to the extrusion ( afaik, THREE's native shapes are drawn on an x,y plane to be extruded on the z plane, it seems like deriving a `vector2` from `MapboxGl.MercatorCoordinate.fromLngLat([lng, lat], 0)` is maybe missing a relative matrix transform resulting in an incorrect evaluation of the final geometry ) and / or a matrix transform is missing from the eventual `ExtrudeGeometry` which is currently being extruded on the z axis ( as it would be in a typical THREE environment ) but in this maps environment ( I'd expect ) would rather be extuded on the Y ( or up ) axis away from the  maps "floor" with the same behaviour as map boxes native 2.5D layer's `"fill-extrusion-height"`

would you know or atleast have any idea why this may be happening? Is it left down to user land to implement the correct transforms for this? if so would you know how I'd apply the correct matrix transforms and and which stage? If it's not intentional and not intentionally user land issues is this something valuable worth pointing out for a potential update to support `<extrudeGeometry/>` with shapes?

Thanks for your effort on creating this Library, it's a real powerhouse in itself!

**Comment by forerunrun** [comment]
As an update, the `<Coordinates>` component works perfectly for individual meshes, I'm wondering if there's a way to simply expose the underlying function behond the `<Coordinates>` component so an array of vectors (3 or 2) could be set from the same function and passed to `Shape` and or `BufferGeometry` respectively, this way geometries can be absolutely positioned on the map from their vertex positions...

**Comment by RodrigoHamuy** [comment]
Hi, @forerunrun, thanks! Do you have maybe a sandbox to replicate the issue? R3M (react-three-map) doesn't alter geometries or the scene object matrices, only the camera matrices.

**Comment by RodrigoHamuy** [comment]
@forerunrun the issue is that you are using coordinate points to define a ThreeJS mesh, but as soon as you are in ThreeJS, evertyhing is in meters units. So you need to convert your coordinates to meters. I wrote an example of how to do that [here](https://codesandbox.io/p/sandbox/react-three-map-basic-app-forked-546q2t?file=%2Fsrc%2FApp.tsx%3A41%2C27-41%2C33).

**Comment by forerunrun** [comment]
> I wrote an example of how to do that [here](https://codesandbox.io/p/sandbox/react-three-map-basic-app-forked-546q2t?file=%2Fsrc%2FApp.tsx%3A41%2C27-41%2C33).

oh @RodrigoHamuy that's amazing, i completely overlooked that! one thing is that there seems to be an odd rotation to the shape, the back of the shape, based on the coordinates, should be parralel to the blue line in the following image...
![image](https://github.com/RodrigoHamuy/react-three-map/assets/50278392/5e8ec2f1-3b6a-4f21-974d-b5e4c7075fa1)

would you have an idea why that rotation is off? I'm going to have a proper look into the coordsTovector3 method you've written to try to look into it now...

**Comment by RodrigoHamuy** [comment]
@forerunrun maybe [this version ](https://codesandbox.io/p/sandbox/react-three-map-basic-app-forked-cjj8c5?file=%2Fsrc%2FApp.tsx%3A41%2C27-41%2C33) helps?

**Comment by forerunrun** [comment]
@RodrigoHamuy that's great thank you so much for looking into this, yes helps, i still can't tell why the extrude geometry is off, it should be right, if for instance on the extrude geometry mesh we use `<mesh rotation={[90 * MathUtils.DEG2RAD, 0, 0]}>` rather than -90 the orientation looks correct but the mesh is effectively upside down, both lines and extrusions are really useful in different cases so i'll try getting to the bottom of this! thanks again for your help!

**Comment by RodrigoHamuy** [comment]
@forerunrun, in `coordsTovector3` change from `- angle` to `+ angle` to flip the interpretation. Then you can have your mesh facing Z-up  ([sandbox](https://codesandbox.io/p/sandbox/react-three-map-basic-app-forked-546q2t?file=%2Fsrc%2FApp.tsx%3A41%2C27-41%2C33)) ✌️ 

<img width="227" alt="image" src="https://github.com/RodrigoHamuy/react-three-map/assets/2405611/aa6a3f56-63a6-49bf-84bf-3c7d94cc73bf">

**Comment by forerunrun** [comment]
> in `coordsTovector3` change from `- angle` to `+ angle` to flip the interpretation.

Hey @RodrigoHamuy the problem with that is it then changes the orientation of the <Line/> in the same way... i ended up just changing the scale of the up axis to -1 for the extrude geometry mesh which seems to work...

one other thing i've noticed is the raycasting accuracy is strangely off when the map is zoomed out and an object appears small... for instance in an [official example here](https://codesandbox.io/p/sandbox/vigorous-snyder-2n9vpl?file=%2Fsrc%2FApp.tsx%3A48%2C45)...

![image](https://github.com/RodrigoHamuy/react-three-map/assets/50278392/3fc1df66-7507-4615-84ae-e26a5e47ce47)

in the above image the mouse is currently over the lowest left cube (although you can't see it, it is ) but the onPointerOver event is not being detected for some reason, i'm thinking it's possibly a raycaster misprojection maybe?
