### ISSUE TITLE
Allow to set a custom layer ID, and layer properties

### ISSUE THREAD

**Issue by iduuck** [RodrigoHamuy/react-three-map#67]
I am currently struggling to find a way to set a custom layer ID and layer properties, since the layer is being set **after** all other layers, that's bad, because the 3d model should be **before** (above) all other layers.

This would fix it.

**Comment by RodrigoHamuy** [comment]
Makes sense. If this was a normal `react-map-gl`, what would the properties that you want to set? Can you maybe drop an example like:
```tsx
<Layer id={id} // what else? />
```

**Comment by iduuck** [comment]
The example would look like this:

```jsx
<Layer 
  id="my-custom-id" 
  {...otherProps}
  beforeId="another-layer-id" 
/>
```

My ideal implementation would be:

```jsx
<Canvas 
  id="my-custom-id" 
  beforeId="another-layer-id" 
>
  {/* Models/Coordinates here */}
</Canvas>
```

I see, that we are setting an ID based on the `useId` given to us by React. But this is not the ideal approach in this case, because it's an actual identifier rather than a key identifying the react element.

**Comment by iduuck** [comment]
Just tried to implement this myself. Didn't test it though, #70.

**Comment by rodrigomodulous** [comment]
Fixed in https://github.com/RodrigoHamuy/react-three-map/pull/76

**Comment by RodrigoHamuy** [comment]
Thanks @iduuck! I merged your PR with a few minor changes and should already be available on latest release.
https://github.com/RodrigoHamuy/react-three-map/pull/76
