### ISSUE TITLE
using <EffectComposer> or <Effects> from r3/drei

### ISSUE THREAD

**Issue by forerunrun** [RodrigoHamuy/react-three-map#69]
Is it possible to use the `<EffectComposer>` component from drei within the `<Canvas>` provided by `react-three-map` or is this a current limitation? I tried to get some `<Effects>` in and also tried using `<EffectComposer>` but all setups seem to clear the render buffers resulting in the mapbox render not being renderered under the three scene...

I was going to have a look into the possible upcoming features now to see if this is already documented, if not do you think this will be a possible future feature @RodrigoHamuy ?

**EDIT:** I see here there's a postprocessing _todo_  https://github.com/users/RodrigoHamuy/projects/1?pane=issue&itemId=31099754 is this still in the pipeline to be worked on or do you think it's not possble currently?

**Comment by RodrigoHamuy** [comment]
This is now possible through the `overlay` prop:
https://rodrigohamuy.github.io/react-three-map/?story=postprocessing--default
Cc @forerunrun
