### ISSUE TITLE
Pinpoint scale effect

### ISSUE THREAD

**Issue by cyango** [RodrigoHamuy/react-three-map#72]
Hi i wanted to know if it's possible to zoom in and out and that scales up and down the pinpoint so we can always see it on the map?

**Comment by RodrigoHamuy** [comment]
This is a common feature even in a normal ThreeJS to implement things like gizmos, so I'm not sure if this is something that `react-three-map` should solve? But you add [this component](https://github.com/RodrigoHamuy/react-three-map/blob/main/stories/src/screen-sizer.tsx) (just copy paste it) as a way to solve that problem. It will convert meters to pixel scale. So 1 ThreeJS unit becomes 1 pixel width.

```ts
<ScreenSizer><Box /></ScreenSizer>
```
