### ISSUE TITLE
Integration inside another canvas

### ISSUE THREAD

**Issue by cyango** [RodrigoHamuy/react-three-map#73]
As Map is a wrapper of canvas, many apps still need to access the canvas states. Is it possible to isolate the map in a secondary canvas inside the main canvas, and both being able to communicate?
Is this feasible in a WebXR environment?

**Comment by RodrigoHamuy** [comment]
What kind of data are you trying to get? Or even better if you have an example? Thanks

**Comment by cyango** [comment]
I would like to implement maps interaction inside a XRCanvas from this repo: https://github.com/coconut-xr/natuerlich

**Comment by cyango** [comment]
Just curious why have you decided to create a Map wrapper instead of a component that could live inside canvas? Why transforming the whole canvas scene into a map? I'm asking this because of the need of having maps living inside a popup or similar inside the canvas, not the whole scene for example.

Thanks for your attention :)

**Comment by RodrigoHamuy** [comment]
Right. So react-three-map (R3M) works just as another layer in Maplibre/Mapbox, so any feature from MapLibre/Box works just as usual, and on top you can render things in ThreeJS. 

Doing the other way around would be a different tool, not something in the scope of R3M atm.

I'm not familiar with `natuerlich`, so my advice is limited here, but I guess one thing you could do is copy the Maplibre DOM to a ThreeJS texture that you could render to `natuerlich`? But that is as good as it gets if you want to use this tool I'm afraid.
