### ISSUE TITLE
Examples Error

### ISSUE THREAD

**Issue by lucas-vitrus** [RodrigoHamuy/react-three-map#95]
# Error on Sun Light example

Recently I've encountered this error on the Examples page:
```
TypeError: Cannot read properties of undefined (reading 'cssRules')
    at Cc (mapbox-gl-CEFP40r5.js:1:42645)
    at r (mapbox-gl-CEFP40r5.js:1:42589)
    at Sc (mapbox-gl-CEFP40r5.js:1:42607)
    at mapbox-gl-CEFP40r5.js:1:48092
    at mapbox-gl-CEFP40r5.js:1:34409
    at mapbox-gl-CEFP40r5.js:1:47732
    at Fc (mapbox-gl-CEFP40r5.js:1:48352)
    at mapbox-gl-CEFP40r5.js:1:97486
```

<img width="1728" alt="image" src="https://github.com/RodrigoHamuy/react-three-map/assets/133435610/2ba47460-bd74-491d-8ed6-a2b7b1e0a67d">

**Comment by RodrigoHamuy** [comment]
@lucas-vitrus  In the meantime if you refresh it will work, as it seems to run each story fine on page reload but breaks when navigating between stories. When I have some free time will check what happened.
